'use strict';

const COMMAND_REGISTRY = [
  {
    name: '/pending',
    argumentHint: '',
    shortDescription: 'List pending queue items.',
    details: 'Writes a command block with the next queue item and the remaining pending items.',
    examples: ['/pending'],
    category: 'Queue',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/send',
    argumentHint: '<id>',
    shortDescription: 'Send a pending queue item.',
    details: 'Uses the same backend path as the Send button on a queue item. If a prompt is already running, the item is moved next.',
    examples: ['/send abc123'],
    category: 'Queue',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: true,
  },
  {
    name: '/next',
    argumentHint: '<id>',
    shortDescription: 'Move a pending item next.',
    details: 'Moves a pending queue item directly after the current running item, or to the first pending position when idle. It does not resume a paused queue or start processing.',
    examples: ['/next abc123'],
    category: 'Queue',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: true,
  },
  {
    name: '/schedule',
    argumentHint: '[time|reset]',
    shortDescription: 'Open or update queue schedule.',
    details: 'Without arguments, opens the schedule modal. With reset, clears the schedule. With a time value, schedules the queue through the backend schedule path.',
    examples: ['/schedule', '/schedule reset', '/schedule 10m', '/schedule 1h 30m', '/schedule 2026-07-05 18:30'],
    category: 'Queue',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/sandbox',
    argumentHint: '[mode]',
    shortDescription: 'Show or change sandbox mode.',
    details: 'Without arguments, prints the current sandbox mode and available modes. With a mode, updates Codex Web config and uses that sandbox policy for future Codex turns.',
    examples: ['/sandbox', '/sandbox read-only', '/sandbox workspace-write', '/sandbox danger-full-access'],
    category: 'Config',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
    options: ['read-only', 'workspace-write', 'danger-full-access'],
    optionDescriptions: {
      'read-only': 'Run future turns with read-only filesystem access.',
      'workspace-write': 'Allow future turns to write inside the workspace.',
      'danger-full-access': 'Run future turns without normal sandbox filesystem restrictions.',
    },
  },
  {
    name: '/approval',
    argumentHint: '[policy]',
    shortDescription: 'Show or change approval policy.',
    details: 'Without arguments, prints the current approval policy and available policies. With a policy, updates Codex Web config and uses that approval policy for future Codex turns.',
    examples: ['/approval', '/approval on-request', '/approval never', '/approval on-failure'],
    category: 'Config',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
    options: ['on-request', 'never', 'untrusted', 'on-failure'],
    optionDescriptions: {
      'on-request': 'Ask for approval when an action needs elevated permissions.',
      never: 'Do not ask for approval; run only what current permissions allow.',
      untrusted: 'Require approval for more actions in an untrusted workflow.',
      'on-failure': 'Ask for approval only after an action fails under sandbox restrictions.',
    },
  },
  {
    name: '/compact',
    argumentHint: '',
    shortDescription: 'Compact the current session context.',
    details: 'Adds a queued command that asks the Codex app-server to compact the current session. It runs in queue order, reports compact usage, and the queue continues after compaction completes.',
    examples: ['/compact'],
    category: 'Queue',
    execution: 'queued',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/pause',
    argumentHint: '',
    shortDescription: 'Pause automatic queue processing.',
    details: 'Stops countdowns and prevents the queue from sending the next pending item until you resume it. Existing active work is not interrupted by this command.',
    examples: ['/pause'],
    category: 'Queue',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/resume',
    argumentHint: '',
    shortDescription: 'Resume queue processing.',
    details: 'Restarts automatic processing. During a manual send, it arms continuation so the queue resumes after the active prompt finishes.',
    examples: ['/resume'],
    category: 'Queue',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/undo',
    argumentHint: '',
    shortDescription: 'Undo the latest queue add or cancel a waiting steer.',
    details: 'Walks the last few undoable actions. Pending queue additions are removed and restored to the composer. Waiting /think notes are canceled before the steer request is accepted. Already-sent steers cannot be undone.',
    examples: ['/undo'],
    category: 'Queue',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/clear',
    argumentHint: '',
    shortDescription: 'Clear pending queue items.',
    details: 'Removes all pending prompts from the queue. Completed, failed, cancelled, interrupted, and running items are left untouched.',
    examples: ['/clear'],
    category: 'Queue',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/stop',
    argumentHint: '',
    shortDescription: 'Interrupt the active prompt.',
    details: 'Interrupts the active prompt without a confirmation modal. It leaves the local server running.',
    examples: ['/stop'],
    category: 'Execution',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/think',
    argumentHint: '<instruction>',
    displayArgumentHint: '<text>',
    shortDescription: 'Steer the active prompt.',
    details: 'Sends a note to the currently running turn with turn/steer. Use it when the model is working but you want to adjust direction after the next tool boundary. It does not create a queue item, change queue order, or mark the active queue item failed.',
    examples: ['/think Focus on the queue-state bug first.', '/think Ignore the styling change for now and finish the tests.'],
    category: 'Steering',
    execution: 'steer',
    autocomplete: true,
    requiresArgs: true,
  },
  {
    name: '/think!',
    argumentHint: '[instruction]',
    displayArgumentHint: '<text>',
    shortDescription: 'Interrupt and send a correction.',
    details: 'With text, interrupts the active turn and sends the text as a follow-up prompt. Without text, converts the latest waiting /think note into an interrupting follow-up. If limits are unavailable, Codex Web asks for confirmation before interrupting because the correction may need to wait.',
    examples: ['/think!', '/think! Stop this approach. Rework it through the backend event flow.'],
    category: 'Steering',
    execution: 'steer',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/approve',
    argumentHint: '',
    shortDescription: 'Approve the current request once.',
    details: 'Responds to the current approval request with a one-time accept decision. Use it when the approval prompt is visible and you want to allow only this specific action.',
    examples: ['/approve'],
    category: 'Approval',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/approve-session',
    argumentHint: '',
    shortDescription: 'Approve requests for the session.',
    details: 'Responds to the current approval request with an accept-for-session decision when the app-server supports it. This is useful for repeated similar actions in the same session.',
    examples: ['/approve-session'],
    category: 'Approval',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/decline',
    argumentHint: '',
    shortDescription: 'Decline the current approval request.',
    details: 'Responds to the current approval request with a decline decision. The active turn can continue only if the app-server can recover from the declined action.',
    examples: ['/decline'],
    category: 'Approval',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/cancel',
    argumentHint: '',
    shortDescription: 'Cancel the current approval request.',
    details: 'Responds to the current approval request with a cancel decision. Use it when you want to stop the pending approval flow rather than approve or decline it.',
    examples: ['/cancel'],
    category: 'Approval',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/help',
    argumentHint: '',
    shortDescription: 'Show this command reference.',
    details: 'Opens the command help dialog with short descriptions, detailed explanations, and examples for every supported command.',
    examples: ['/help'],
    category: 'App',
    execution: 'frontend-only',
    autocomplete: true,
    requiresArgs: false,
  },
  {
    name: '/quit',
    argumentHint: '',
    shortDescription: 'Shut down the local server.',
    details: 'Shuts down the local web server and the Codex app-server process. Open a new codex-web instance to continue after this command.',
    examples: ['/quit'],
    category: 'App',
    execution: 'backend-executed',
    autocomplete: true,
    requiresArgs: false,
  },
];

function cloneCommand(entry) {
  const hint = entry.displayArgumentHint || entry.argumentHint || '';
  return {
    ...entry,
    command: `${entry.name}${hint ? ` ${hint}` : ''}`,
    short: entry.shortDescription,
    kind: entry.category,
    examples: [...entry.examples],
  };
}

function commandHelpPayload() {
  return COMMAND_REGISTRY.map(cloneCommand);
}

function commandMetadataPayload() {
  return COMMAND_REGISTRY.map((entry) => ({ ...entry, examples: [...entry.examples] }));
}

function commandByName(name) {
  return COMMAND_REGISTRY.find((entry) => entry.name === name) || null;
}

function isQueuedCommandName(name) {
  const entry = commandByName(name);
  return !!entry && entry.execution === 'queued';
}

module.exports = {
  COMMAND_REGISTRY,
  COMMAND_HELP: commandHelpPayload(),
  commandHelpPayload,
  commandMetadataPayload,
  commandByName,
  isQueuedCommandName,
};
